# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/a-res/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/a-res/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a-res/src/CMakeFiles /home/a-res/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a-res/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fg_server

# Build rule for target.
fg_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fg_server
.PHONY : fg_server

# fast build rule for target.
fg_server/fast:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/build
.PHONY : fg_server/fast

#=============================================================================
# Target rules for targets named Plib

# Build rule for target.
Plib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plib
.PHONY : Plib

# fast build rule for target.
Plib/fast:
	$(MAKE) -f CMakeFiles/Plib.dir/build.make CMakeFiles/Plib.dir/build
.PHONY : Plib/fast

#=============================================================================
# Target rules for targets named Multiplayer

# Build rule for target.
Multiplayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Multiplayer
.PHONY : Multiplayer

# fast build rule for target.
Multiplayer/fast:
	$(MAKE) -f CMakeFiles/Multiplayer.dir/build.make CMakeFiles/Multiplayer.dir/build
.PHONY : Multiplayer/fast

#=============================================================================
# Target rules for targets named LibCLI

# Build rule for target.
LibCLI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibCLI
.PHONY : LibCLI

# fast build rule for target.
LibCLI/fast:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/build
.PHONY : LibCLI/fast

#=============================================================================
# Target rules for targets named SGUtils

# Build rule for target.
SGUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SGUtils
.PHONY : SGUtils

# fast build rule for target.
SGUtils/fast:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/build
.PHONY : SGUtils/fast

#=============================================================================
# Target rules for targets named fgms

# Build rule for target.
fgms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fgms
.PHONY : fgms

# fast build rule for target.
fgms/fast:
	$(MAKE) -f CMakeFiles/fgms.dir/build.make CMakeFiles/fgms.dir/build
.PHONY : fgms/fast

src/flightgear/MultiPlayer/tiny_xdr.o: src/flightgear/MultiPlayer/tiny_xdr.cxx.o

.PHONY : src/flightgear/MultiPlayer/tiny_xdr.o

# target to build an object file
src/flightgear/MultiPlayer/tiny_xdr.cxx.o:
	$(MAKE) -f CMakeFiles/Multiplayer.dir/build.make CMakeFiles/Multiplayer.dir/src/flightgear/MultiPlayer/tiny_xdr.cxx.o
.PHONY : src/flightgear/MultiPlayer/tiny_xdr.cxx.o

src/flightgear/MultiPlayer/tiny_xdr.i: src/flightgear/MultiPlayer/tiny_xdr.cxx.i

.PHONY : src/flightgear/MultiPlayer/tiny_xdr.i

# target to preprocess a source file
src/flightgear/MultiPlayer/tiny_xdr.cxx.i:
	$(MAKE) -f CMakeFiles/Multiplayer.dir/build.make CMakeFiles/Multiplayer.dir/src/flightgear/MultiPlayer/tiny_xdr.cxx.i
.PHONY : src/flightgear/MultiPlayer/tiny_xdr.cxx.i

src/flightgear/MultiPlayer/tiny_xdr.s: src/flightgear/MultiPlayer/tiny_xdr.cxx.s

.PHONY : src/flightgear/MultiPlayer/tiny_xdr.s

# target to generate assembly for a file
src/flightgear/MultiPlayer/tiny_xdr.cxx.s:
	$(MAKE) -f CMakeFiles/Multiplayer.dir/build.make CMakeFiles/Multiplayer.dir/src/flightgear/MultiPlayer/tiny_xdr.cxx.s
.PHONY : src/flightgear/MultiPlayer/tiny_xdr.cxx.s

src/libcli/cli_client.o: src/libcli/cli_client.cxx.o

.PHONY : src/libcli/cli_client.o

# target to build an object file
src/libcli/cli_client.cxx.o:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/cli_client.cxx.o
.PHONY : src/libcli/cli_client.cxx.o

src/libcli/cli_client.i: src/libcli/cli_client.cxx.i

.PHONY : src/libcli/cli_client.i

# target to preprocess a source file
src/libcli/cli_client.cxx.i:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/cli_client.cxx.i
.PHONY : src/libcli/cli_client.cxx.i

src/libcli/cli_client.s: src/libcli/cli_client.cxx.s

.PHONY : src/libcli/cli_client.s

# target to generate assembly for a file
src/libcli/cli_client.cxx.s:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/cli_client.cxx.s
.PHONY : src/libcli/cli_client.cxx.s

src/libcli/debug.o: src/libcli/debug.cxx.o

.PHONY : src/libcli/debug.o

# target to build an object file
src/libcli/debug.cxx.o:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/debug.cxx.o
.PHONY : src/libcli/debug.cxx.o

src/libcli/debug.i: src/libcli/debug.cxx.i

.PHONY : src/libcli/debug.i

# target to preprocess a source file
src/libcli/debug.cxx.i:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/debug.cxx.i
.PHONY : src/libcli/debug.cxx.i

src/libcli/debug.s: src/libcli/debug.cxx.s

.PHONY : src/libcli/debug.s

# target to generate assembly for a file
src/libcli/debug.cxx.s:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/debug.cxx.s
.PHONY : src/libcli/debug.cxx.s

src/libcli/filter.o: src/libcli/filter.cxx.o

.PHONY : src/libcli/filter.o

# target to build an object file
src/libcli/filter.cxx.o:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/filter.cxx.o
.PHONY : src/libcli/filter.cxx.o

src/libcli/filter.i: src/libcli/filter.cxx.i

.PHONY : src/libcli/filter.i

# target to preprocess a source file
src/libcli/filter.cxx.i:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/filter.cxx.i
.PHONY : src/libcli/filter.cxx.i

src/libcli/filter.s: src/libcli/filter.cxx.s

.PHONY : src/libcli/filter.s

# target to generate assembly for a file
src/libcli/filter.cxx.s:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/filter.cxx.s
.PHONY : src/libcli/filter.cxx.s

src/libcli/libcli.o: src/libcli/libcli.cxx.o

.PHONY : src/libcli/libcli.o

# target to build an object file
src/libcli/libcli.cxx.o:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/libcli.cxx.o
.PHONY : src/libcli/libcli.cxx.o

src/libcli/libcli.i: src/libcli/libcli.cxx.i

.PHONY : src/libcli/libcli.i

# target to preprocess a source file
src/libcli/libcli.cxx.i:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/libcli.cxx.i
.PHONY : src/libcli/libcli.cxx.i

src/libcli/libcli.s: src/libcli/libcli.cxx.s

.PHONY : src/libcli/libcli.s

# target to generate assembly for a file
src/libcli/libcli.cxx.s:
	$(MAKE) -f CMakeFiles/LibCLI.dir/build.make CMakeFiles/LibCLI.dir/src/libcli/libcli.cxx.s
.PHONY : src/libcli/libcli.cxx.s

src/plib/netSocket.o: src/plib/netSocket.cxx.o

.PHONY : src/plib/netSocket.o

# target to build an object file
src/plib/netSocket.cxx.o:
	$(MAKE) -f CMakeFiles/Plib.dir/build.make CMakeFiles/Plib.dir/src/plib/netSocket.cxx.o
.PHONY : src/plib/netSocket.cxx.o

src/plib/netSocket.i: src/plib/netSocket.cxx.i

.PHONY : src/plib/netSocket.i

# target to preprocess a source file
src/plib/netSocket.cxx.i:
	$(MAKE) -f CMakeFiles/Plib.dir/build.make CMakeFiles/Plib.dir/src/plib/netSocket.cxx.i
.PHONY : src/plib/netSocket.cxx.i

src/plib/netSocket.s: src/plib/netSocket.cxx.s

.PHONY : src/plib/netSocket.s

# target to generate assembly for a file
src/plib/netSocket.cxx.s:
	$(MAKE) -f CMakeFiles/Plib.dir/build.make CMakeFiles/Plib.dir/src/plib/netSocket.cxx.s
.PHONY : src/plib/netSocket.cxx.s

src/server/daemon.o: src/server/daemon.cxx.o

.PHONY : src/server/daemon.o

# target to build an object file
src/server/daemon.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/daemon.cxx.o
.PHONY : src/server/daemon.cxx.o

src/server/daemon.i: src/server/daemon.cxx.i

.PHONY : src/server/daemon.i

# target to preprocess a source file
src/server/daemon.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/daemon.cxx.i
.PHONY : src/server/daemon.cxx.i

src/server/daemon.s: src/server/daemon.cxx.s

.PHONY : src/server/daemon.s

# target to generate assembly for a file
src/server/daemon.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/daemon.cxx.s
.PHONY : src/server/daemon.cxx.s

src/server/fg_cli.o: src/server/fg_cli.cxx.o

.PHONY : src/server/fg_cli.o

# target to build an object file
src/server/fg_cli.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_cli.cxx.o
.PHONY : src/server/fg_cli.cxx.o

src/server/fg_cli.i: src/server/fg_cli.cxx.i

.PHONY : src/server/fg_cli.i

# target to preprocess a source file
src/server/fg_cli.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_cli.cxx.i
.PHONY : src/server/fg_cli.cxx.i

src/server/fg_cli.s: src/server/fg_cli.cxx.s

.PHONY : src/server/fg_cli.s

# target to generate assembly for a file
src/server/fg_cli.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_cli.cxx.s
.PHONY : src/server/fg_cli.cxx.s

src/server/fg_config.o: src/server/fg_config.cxx.o

.PHONY : src/server/fg_config.o

# target to build an object file
src/server/fg_config.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_config.cxx.o
.PHONY : src/server/fg_config.cxx.o

src/server/fg_config.i: src/server/fg_config.cxx.i

.PHONY : src/server/fg_config.i

# target to preprocess a source file
src/server/fg_config.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_config.cxx.i
.PHONY : src/server/fg_config.cxx.i

src/server/fg_config.s: src/server/fg_config.cxx.s

.PHONY : src/server/fg_config.s

# target to generate assembly for a file
src/server/fg_config.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_config.cxx.s
.PHONY : src/server/fg_config.cxx.s

src/server/fg_geometry.o: src/server/fg_geometry.cxx.o

.PHONY : src/server/fg_geometry.o

# target to build an object file
src/server/fg_geometry.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_geometry.cxx.o
.PHONY : src/server/fg_geometry.cxx.o

src/server/fg_geometry.i: src/server/fg_geometry.cxx.i

.PHONY : src/server/fg_geometry.i

# target to preprocess a source file
src/server/fg_geometry.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_geometry.cxx.i
.PHONY : src/server/fg_geometry.cxx.i

src/server/fg_geometry.s: src/server/fg_geometry.cxx.s

.PHONY : src/server/fg_geometry.s

# target to generate assembly for a file
src/server/fg_geometry.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_geometry.cxx.s
.PHONY : src/server/fg_geometry.cxx.s

src/server/fg_list.o: src/server/fg_list.cxx.o

.PHONY : src/server/fg_list.o

# target to build an object file
src/server/fg_list.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_list.cxx.o
.PHONY : src/server/fg_list.cxx.o

src/server/fg_list.i: src/server/fg_list.cxx.i

.PHONY : src/server/fg_list.i

# target to preprocess a source file
src/server/fg_list.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_list.cxx.i
.PHONY : src/server/fg_list.cxx.i

src/server/fg_list.s: src/server/fg_list.cxx.s

.PHONY : src/server/fg_list.s

# target to generate assembly for a file
src/server/fg_list.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_list.cxx.s
.PHONY : src/server/fg_list.cxx.s

src/server/fg_server.o: src/server/fg_server.cxx.o

.PHONY : src/server/fg_server.o

# target to build an object file
src/server/fg_server.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_server.cxx.o
.PHONY : src/server/fg_server.cxx.o

src/server/fg_server.i: src/server/fg_server.cxx.i

.PHONY : src/server/fg_server.i

# target to preprocess a source file
src/server/fg_server.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_server.cxx.i
.PHONY : src/server/fg_server.cxx.i

src/server/fg_server.s: src/server/fg_server.cxx.s

.PHONY : src/server/fg_server.s

# target to generate assembly for a file
src/server/fg_server.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_server.cxx.s
.PHONY : src/server/fg_server.cxx.s

src/server/fg_tracker.o: src/server/fg_tracker.cxx.o

.PHONY : src/server/fg_tracker.o

# target to build an object file
src/server/fg_tracker.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_tracker.cxx.o
.PHONY : src/server/fg_tracker.cxx.o

src/server/fg_tracker.i: src/server/fg_tracker.cxx.i

.PHONY : src/server/fg_tracker.i

# target to preprocess a source file
src/server/fg_tracker.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_tracker.cxx.i
.PHONY : src/server/fg_tracker.cxx.i

src/server/fg_tracker.s: src/server/fg_tracker.cxx.s

.PHONY : src/server/fg_tracker.s

# target to generate assembly for a file
src/server/fg_tracker.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_tracker.cxx.s
.PHONY : src/server/fg_tracker.cxx.s

src/server/fg_util.o: src/server/fg_util.cxx.o

.PHONY : src/server/fg_util.o

# target to build an object file
src/server/fg_util.cxx.o:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_util.cxx.o
.PHONY : src/server/fg_util.cxx.o

src/server/fg_util.i: src/server/fg_util.cxx.i

.PHONY : src/server/fg_util.i

# target to preprocess a source file
src/server/fg_util.cxx.i:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_util.cxx.i
.PHONY : src/server/fg_util.cxx.i

src/server/fg_util.s: src/server/fg_util.cxx.s

.PHONY : src/server/fg_util.s

# target to generate assembly for a file
src/server/fg_util.cxx.s:
	$(MAKE) -f CMakeFiles/fg_server.dir/build.make CMakeFiles/fg_server.dir/src/server/fg_util.cxx.s
.PHONY : src/server/fg_util.cxx.s

src/server/main.o: src/server/main.cxx.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cxx.o:
	$(MAKE) -f CMakeFiles/fgms.dir/build.make CMakeFiles/fgms.dir/src/server/main.cxx.o
.PHONY : src/server/main.cxx.o

src/server/main.i: src/server/main.cxx.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cxx.i:
	$(MAKE) -f CMakeFiles/fgms.dir/build.make CMakeFiles/fgms.dir/src/server/main.cxx.i
.PHONY : src/server/main.cxx.i

src/server/main.s: src/server/main.cxx.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cxx.s:
	$(MAKE) -f CMakeFiles/fgms.dir/build.make CMakeFiles/fgms.dir/src/server/main.cxx.s
.PHONY : src/server/main.cxx.s

src/simgear/debug/logstream.o: src/simgear/debug/logstream.cxx.o

.PHONY : src/simgear/debug/logstream.o

# target to build an object file
src/simgear/debug/logstream.cxx.o:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/debug/logstream.cxx.o
.PHONY : src/simgear/debug/logstream.cxx.o

src/simgear/debug/logstream.i: src/simgear/debug/logstream.cxx.i

.PHONY : src/simgear/debug/logstream.i

# target to preprocess a source file
src/simgear/debug/logstream.cxx.i:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/debug/logstream.cxx.i
.PHONY : src/simgear/debug/logstream.cxx.i

src/simgear/debug/logstream.s: src/simgear/debug/logstream.cxx.s

.PHONY : src/simgear/debug/logstream.s

# target to generate assembly for a file
src/simgear/debug/logstream.cxx.s:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/debug/logstream.cxx.s
.PHONY : src/simgear/debug/logstream.cxx.s

src/simgear/math/SGEuler.o: src/simgear/math/SGEuler.cxx.o

.PHONY : src/simgear/math/SGEuler.o

# target to build an object file
src/simgear/math/SGEuler.cxx.o:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/math/SGEuler.cxx.o
.PHONY : src/simgear/math/SGEuler.cxx.o

src/simgear/math/SGEuler.i: src/simgear/math/SGEuler.cxx.i

.PHONY : src/simgear/math/SGEuler.i

# target to preprocess a source file
src/simgear/math/SGEuler.cxx.i:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/math/SGEuler.cxx.i
.PHONY : src/simgear/math/SGEuler.cxx.i

src/simgear/math/SGEuler.s: src/simgear/math/SGEuler.cxx.s

.PHONY : src/simgear/math/SGEuler.s

# target to generate assembly for a file
src/simgear/math/SGEuler.cxx.s:
	$(MAKE) -f CMakeFiles/SGUtils.dir/build.make CMakeFiles/SGUtils.dir/src/simgear/math/SGEuler.cxx.s
.PHONY : src/simgear/math/SGEuler.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... fg_server"
	@echo "... Plib"
	@echo "... Multiplayer"
	@echo "... LibCLI"
	@echo "... SGUtils"
	@echo "... fgms"
	@echo "... src/flightgear/MultiPlayer/tiny_xdr.o"
	@echo "... src/flightgear/MultiPlayer/tiny_xdr.i"
	@echo "... src/flightgear/MultiPlayer/tiny_xdr.s"
	@echo "... src/libcli/cli_client.o"
	@echo "... src/libcli/cli_client.i"
	@echo "... src/libcli/cli_client.s"
	@echo "... src/libcli/debug.o"
	@echo "... src/libcli/debug.i"
	@echo "... src/libcli/debug.s"
	@echo "... src/libcli/filter.o"
	@echo "... src/libcli/filter.i"
	@echo "... src/libcli/filter.s"
	@echo "... src/libcli/libcli.o"
	@echo "... src/libcli/libcli.i"
	@echo "... src/libcli/libcli.s"
	@echo "... src/plib/netSocket.o"
	@echo "... src/plib/netSocket.i"
	@echo "... src/plib/netSocket.s"
	@echo "... src/server/daemon.o"
	@echo "... src/server/daemon.i"
	@echo "... src/server/daemon.s"
	@echo "... src/server/fg_cli.o"
	@echo "... src/server/fg_cli.i"
	@echo "... src/server/fg_cli.s"
	@echo "... src/server/fg_config.o"
	@echo "... src/server/fg_config.i"
	@echo "... src/server/fg_config.s"
	@echo "... src/server/fg_geometry.o"
	@echo "... src/server/fg_geometry.i"
	@echo "... src/server/fg_geometry.s"
	@echo "... src/server/fg_list.o"
	@echo "... src/server/fg_list.i"
	@echo "... src/server/fg_list.s"
	@echo "... src/server/fg_server.o"
	@echo "... src/server/fg_server.i"
	@echo "... src/server/fg_server.s"
	@echo "... src/server/fg_tracker.o"
	@echo "... src/server/fg_tracker.i"
	@echo "... src/server/fg_tracker.s"
	@echo "... src/server/fg_util.o"
	@echo "... src/server/fg_util.i"
	@echo "... src/server/fg_util.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/simgear/debug/logstream.o"
	@echo "... src/simgear/debug/logstream.i"
	@echo "... src/simgear/debug/logstream.s"
	@echo "... src/simgear/math/SGEuler.o"
	@echo "... src/simgear/math/SGEuler.i"
	@echo "... src/simgear/math/SGEuler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

